(define-macro (require filepath . symbols)
  ;;(message-string "require:" symbols)
  (let* ((path (eval filepath))
	 (lpath (util-load-path path)))
    `(when (let ((need-to-load #f))
	     (define (sym-defined? symbol)
	       (if (catcherr (lambda(err) #t) (begin (eval symbol) #f))
		   (set! need-to-load #t)))
	     (for-each sym-defined? (quote ,symbols))
	     need-to-load)
       (message-string "require-load:" ,path (quote ,symbols))
       (load ,lpath))))

(gimp-message "require.scm loaded")
